const dubaiAreas = [
  // Downtown and Business Districts
  "Downtown Dubai",
  "Business Bay",
  "Dubai International Financial Centre (DIFC)",
  "Dubai Design District (d3)",
  "Dubai Internet City",
  "Dubai Media City",
  "Knowledge Village",
  "Jumeirah Lake Towers (JLT)",
  "Dubai Silicon Oasis",
  "Dubai Production City",

  // Coastal Areas and Artificial Islands
  "Palm Jumeirah",
  "Jumeirah",
  "Jumeirah Beach Residence (JBR)",
  "Dubai Marina",
  "Bluewaters Island",
  "Deira Islands",
  "The World Islands",
  "La Mer",
  "Jumeirah Islands",
  "Pearl Jumeirah",
  "Dubai Harbour",
  "Dubai Creek Harbour",

  // Luxury Residential Areas
  "Emirates Hills",
  "Al Barari",
  "Dubai Hills Estate",
  "Arabian Ranches",
  "Arabian Ranches 2",
  "Jumeirah Park",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Damac Hills",
  "Damac Hills 2 (Akoya)",
  "Palm Jebel Ali",
  "Mohammad Bin Rashid City (MBR City)",
  "Tilal Al Ghaf",

  // Traditional and Historic Areas
  "Al Fahidi",
  "Bur Dubai",
  "Deira",
  "Al Karama",
  "Al Satwa",
  "Al Ghurair",
  "Al Qusais",
  "Al Rashidiya",
  "Al Mankhool",
  "Hor Al Anz",
  "Al Nahda",

  // Family and Mid-Range Residential Areas
  "Al Barsha",
  "Al Barsha South",
  "The Greens",
  "The Views",
  "The Springs",
  "The Meadows",
  "Discovery Gardens",
  "International City",
  "Sports City",
  "Motor City",
  "Remraam",
  "Dubai South",
  "Al Furjan",
  "Al Warqa",
  "Mirdif",
  "Muhaisnah",
  "Nad Al Sheba",
  "Dubai Silicon Oasis",
  "Dubailand",
  "Al Mizhar",
  "Al Twar",

  // Newer Developments
  "Dubai Creek Harbour",
  "Bluewaters Island",
  "Emaar Beachfront",
  "Dubai Hills Estate",
  "Town Square",
  "Meydan",
  "Hartland",
  "Serena",
  "Mudon",
  "Dubai Wharf",
  "The Lagoons",
  "City Walk",
  "Wasl Gate",
  "Villanova",
  "Dubai Studio City",
  "Academic City",
  "Wadi Al Safa",

  // Industrial and Commercial Areas
  "Al Quoz",
  "Dubai Investment Park",
  "Jebel Ali",
  "Al Qusais Industrial Area",
  "Ras Al Khor Industrial Area",
  "Dubai Industrial City",
];

export default dubaiAreas;
